# Generated by Django 4.0.3 on 2022-03-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_content',
            field=models.CharField(default='Hello World', max_length=300),
            preserve_default=False,
        ),
    ]
